@startuml

class folder {
    id
    name
    type
    full_name
    folder_id
    sort_order
}
note top of folder
    Types: 
    project, 
    context, 
    etc...
end note

class action {
    id
    head
    body
}

class action_in_folder {
    folder_id
    action_id
    sort_order
}

folder "1" -r- "*" action_in_folder
action "1" -l- "*" action_in_folder
folder "1" -l- "*" folder

class share {
    id
}

class address {
    id
    name
    url
}

class share_subscription {
    share_id
    address_id
    status
}
note top of share_subscription
    Statuses:
    new,
    subscribed,
    etc...
end note

share "1" -- "*" share_subscription
share_subscription "*" -- "1" address

class folder_in_share {
    folder_id
    share_id
    uuid
}

class action_in_share {
    action_id
    share_id
    uuid
}

folder "1" -- "*" folder_in_share
action "1" -- "*" action_in_share
folder_in_share "*" -- "1" share
action_in_share "*" -- "1" share

class event {
    id
    type
    timestamp
    author ??
}
note right of event
    Types: 
    add_action, 
    add_folder, 
    change_action, 
    change_folder,
    delete_action,
    delete_folder,
    copy_action,
    move_folder,
    resorting_actions,
    resorting_folders,
    etc...
end note

class folder_log {
    event_id
    name
    type
    full_name ??
    folder_guid ??
    sort_order ??
}

class action_log {
    event_id
    head
    body
}

class action_in_folder_log {
    event_id
    folder_id ??
    action_id ??
    sort_order ??
}

folder "1" -d- "*" folder_log
action "1" -d- "*" action_log
action_in_folder "1" -d- "*" action_in_folder_log
event "1" -u- "0..1" action_log
event "1" -u- "0..1" folder_log
event "1" -u- "0..1" action_in_folder_log
folder_log "1" -r- "*" action_in_folder_log
action_log "1" -l- "*" action_in_folder_log

@enduml
